### ISSUE TITLE
[BUG]:Linkedin Button on homepage is not working

### ISSUE THREAD

**Issue by AyushRay06** [AyushRay06/portfolio-web#2]
LinkedIn redirect button is not working on the home page
![Screenshot 2023-07-24 082625](https://github.com/AyushRay06/portfolio-web/assets/123544230/580d9ff9-4d25-47a0-84e3-304d9a118e49)

**Comment by Aryashakya** [comment]
Hi, I would like to work on this issue.

**Comment by RojusDEV** [comment]
LinkedIn button href attribute is set at "#" so that's why it doesnt work.

**Comment by AyushRay06** [comment]
> Hi, I would like to work on this issue.

sure.

**Comment by AyushRay06** [comment]
> LinkedIn button href attribute is set at "#" so that's why it doesn't work.

This issue is currently assigned . You can contribute to a similar issue #6. 
Here's the Facebook href https://www.facebook.com/ayush.kumartay

**Comment by Aryashakya** [comment]
What is the link to the Linkedin profile?

**Comment by AyushRay06** [comment]
https://www.linkedin.com/in/ayush-ray-06494324a/

**Comment by Aryashakya** [comment]
Please review it #8
