### ISSUE TITLE
[BUG]: About needs upgradation.

### ISSUE THREAD

**Issue by AyushRay06** [AyushRay06/portfolio-web#3]
#Steps to Reproduce:
Go to the home page.
Check the About Section
![git issue about](https://github.com/AyushRay06/portfolio-web/assets/123544230/b57ce8d2-11ed-49d4-b747-dc6859aa96f0)

#Expected Change:
DevOps as a profession and some more details

**Comment by AdityaSahu786** [comment]
Hey Ayush i can solve this problem , but can you be more specific for the about section please.

**Comment by AyushRay06** [comment]
> Hey Ayush i can solve this problem, but can you be more specific for the About section please?

Update the About section to DevOps Engg who knows MERN stack, tolls like Docker, Ansible, Kubernetes, terraform, and cloud.
Update the hi I am DevOps Enthusiast to Engg
